# Generated by Django 5.1.1 on 2024-09-22 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique access code for customer.', max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email associated with the product.', max_length=254)),
                ('password', models.CharField(help_text='Password associated with the product.', max_length=255)),
                ('activation_code', models.CharField(help_text='Activation code for the product.', max_length=100)),
                ('product_link', models.URLField(help_text='URL link for the product.')),
                ('description', models.TextField(help_text='Description of the product.')),
                ('access_code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_details', to='app.accesscode')),
            ],
        ),
    ]
